spring:
  datasource:
    url: jdbc:postgresql://localhost:8880/Post
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql  
    database-platform: 
    show-sql: true

    